version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - docker_release:
          context: org-global
          filters:
            branches:
              only: master

jobs:

  build:
    docker:
      - image: previousnext/golang:1.13
    working_directory: /go/src/github.com/previousnext/notify
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run: go get golang.org/x/lint/golint
      - run:
          name: Run linting
          command: make lint

  docker_release:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      - APP_NAME: notify
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Build and Deploy
          command: |
            VERSION=$(git describe --tags --always)
            echo "Building version: ${VERSION}"
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --pull -t previousnext/${APP_NAME}:${VERSION} -t previousnext/${APP_NAME}:latest $(pwd)
            docker push previousnext/${APP_NAME}:${VERSION}
